### ISSUE TITLE
Scroll position in teletext gets lost when rotating device 

### ISSUE THREAD

**Issue by mmc20520** [livodeu/FreeHamburger#1]
Screen rotation can make scroll position lost in teletext

For example, open teletext and scroll to bottom
<img width="306" alt="Screen Shot 2022-03-03 at 4 55 35 PM" src="https://user-images.githubusercontent.com/100833575/156531006-8ca98992-f1ff-49cf-a184-0face85155d8.png">

Rotate to horizontal and then back to vertical
<img width="301" alt="Screen Shot 2022-03-03 at 4 55 48 PM" src="https://user-images.githubusercontent.com/100833575/156530923-1c25c069-8f37-4118-824f-eeb6a9db4f5e.png">

You can see an inconsistent scroll position. I was testing V 1.1 on an Android emulator running Android 10.

**Comment by littlecd** [comment]
Hi, I observed some other related issues. For example, if you open teletext, press the home button and then try to re-enter the app, you will find teletext disappears. And sometimes when you open the navigation drawers in teletext and rotate screen, seems the web page is still refreshed.
