### ISSUE TITLE
Ability to select text 

### ISSUE THREAD

**Issue by ghost** [livodeu/FreeHamburger#2]
I use "Hamburger" to learn German as a foreign language. Therefore, while reading I have to consult a dictionary very often but the App does not allow me to "select text". Instead, users have to manually type on a Dictionary App every unknown word.

Could you please allow to "select text" by tapping over a word ?

---------
PS. On Android, I use as a Dictionary App "DictTango". German dictionaries are available here: https://forum.freemdict.com/c/19-category/19

**Comment by livodeu** [comment]
This looks easy, but unfortunately isn't. There is a bug somewhere that messes up the display when the text is made selectable.

**Comment by livodeu** [comment]
In the next version it will probably be possible to select text.

**Comment by livodeu** [comment]
This is possible now.
