### ISSUE TITLE
Downloading content to read off-line

### ISSUE THREAD

**Issue by ghost** [livodeu/FreeHamburger#3]
Would it be possible to download all news everyday to read offline ?

**Comment by livodeu** [comment]
I doubt that this is feasible. Think of the content as a web page. Nowadays, one wouldn't download the whole content tree behind a web page.

**Comment by livodeu** [comment]
In the next version it will probably be possible to download individual news articles.

**Comment by livodeu** [comment]
The app now includes an archive.
