### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by carlnickel** [livodeu/FreeHamburger#5]
I love the new UI! And it was even better if you could implement the option for a 'proper' dark mode in dark gray/black colors rather than in dark blue. Would that be possible? thanks!

**Comment by livodeu** [comment]
With v1.5 there are some color styles to choose from. I hope those are close enough to a 'proper' dark mode.

**Comment by carlnickel** [comment]
perfect, thank you very much for this big release!
