### ISSUE TITLE
Unified Push

### ISSUE THREAD

**Issue by topcaser** [livodeu/FreeHamburger#6]
Hi, is it possible to include unified push instead of the polling of new articles?

**Comment by livodeu** [comment]
I'm not sure I fully understand your question but I don't think so since the app does not use/control an application server.

**Comment by topcaser** [comment]
Here it is explained more detailed https://unifiedpush.org/

**Comment by livodeu** [comment]
Well, as this App merely acts as a client and does not know anything about an application server, I don't see any route to take. If anyone has a practical suggestion, don't hesitate…
